### ISSUE TITLE
Mongo Database/Collections

### ISSUE THREAD

**Issue by psaarloos** [Developer-Autodesk/integration-mongo-view.and.data.api#1]
Hi,

The readme file is mentioning something about creating a mongodb database, populated with products matching the "ProductId" of your model. The source seems to be looking for a mongo.materials and mongo.models collection. Could these collections be added to the project as text file to be able to paste it in the Mongo database? This would make it easier to re-create the sample on my own environment. I am using the seat.dwf so all ProductIds should match.

Thanks.

**Comment by leefsmp** [comment]
This is already in the data/models.json file:
[https://github.com/Developer-Autodesk/integration-mongo-view.and.data.api/blob/master/data/models.json](https://github.com/Developer-Autodesk/integration-mongo-view.and.data.api/blob/master/data/models.json)

The other collections will be created by the code if materials do not exist
